export const GET_CONTACTS_LOAD = "GET_CONTACTS_LOAD";
export const GET_CONTACTS_SUCC = "GET_CONTACTS_SUCC";
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";

export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL";

export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_FAIL = "ADD_CONTACT_FAIL";

export const TOGGLE_TRUE = "TOGGLE_TRUE";
export const TOGGLE_FALSE = "TOGGLE_FALSE";

export const GET_ONECONTACT_LOAD = "GET_ONECONTACT_LOAD";
export const GET_ONECONTACT_SUCC = "GET_ONECONTACT_SUCC";
export const GET_ONECONTACT_FAIL = "GET_ONECONTACT_FAIL";

export const UPDATE_CONTACT_SUCC = "UPDATE_ONECONTACT_SUCC";
export const UPDATE_CONTACT_FAIL = "UPDATE_ONECONTACT_FAIL";
